Repository opensource-society/notesvault, pull requests merged in 2025-08, with the labels that each got.

#569 Modifications in Student Account Page
  pages/overview.html
  pages/studentAccount.html
  styling/overview.css
  styling/studentAccount.css
Labels: bug, ui, gssoc2025, level 3

#791 Fixed Highlight Feature
  pages/jotpad.html
  scripts/jotpad.js
  styling/jotpad.css
Labels: enhancement, gssoc2025, level 1, 2⭐⭐, OSCI'25

#869 Fix: #865 - Resolves stats card overflow issue
  LEADERBOARD.md
  README.md
  styling/about.css
  styling/dashboard.css
Labels: 1⭐, OSCI'25

#842 Fix: hide Back-to-Top button when drawer/ footer is visible (#764)
  scripts/script.js
  styling/base.css
Labels: bug, level 1

#802 Add: Screen time tracker
  pages/features.html
  pages/index.html
  pages/study-tracker.html
  scripts/study-tracker.js
  styling/study-tracker.css
Labels: gssoc2025, level 2
